/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 18 10:48:39 GMT 2020
 */

package teapot.pga;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.junit.runner.RunWith;
import teapot.pga.AnalyzerBinary;
import teapot.pga.FileModel;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AnalyzerBinary_ESTest extends AnalyzerBinary_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AnalyzerBinary analyzerBinary0 = new AnalyzerBinary();
      MockFile mockFile0 = new MockFile("(", "(");
      FileModel fileModel0 = new FileModel();
      analyzerBinary0.analyzeFile(mockFile0, fileModel0);
      assertFalse(mockFile0.canExecute());
  }
}
