/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 18 10:52:15 GMT 2020
 */

package teapot.pga;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import teapot.pga.Analyzer;
import teapot.pga.Analyzers;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Analyzers_ESTest extends Analyzers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Analyzer analyzer0 = Analyzers.getAnalyzer(10114);
      assertNotNull(analyzer0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Analyzer analyzer0 = Analyzers.getAnalyzer(20000);
      assertNotNull(analyzer0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Analyzer analyzer0 = Analyzers.getAnalyzer(10098);
      assertNotNull(analyzer0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Analyzer analyzer0 = Analyzers.getAnalyzer(10007);
      assertNotNull(analyzer0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Analyzer analyzer0 = Analyzers.getAnalyzer(1445);
      assertNotNull(analyzer0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Analyzer analyzer0 = Analyzers.getAnalyzer(20009);
      assertNotNull(analyzer0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Analyzers analyzers0 = new Analyzers();
  }
}
