/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 18 10:48:31 GMT 2020
 */

package teapot.pga;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.junit.runner.RunWith;
import teapot.pga.AnalyzerJava;
import teapot.pga.FileModel;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Analyzer_ESTest extends Analyzer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AnalyzerJava analyzerJava0 = new AnalyzerJava();
      MockFile mockFile0 = new MockFile("", "f.Q'\"bG'f'9i`('=");
      FileModel fileModel0 = new FileModel();
      analyzerJava0.analyzeFile(mockFile0, fileModel0);
      assertEquals(0L, fileModel0.getCommentLines());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AnalyzerJava analyzerJava0 = new AnalyzerJava();
      FileModel fileModel0 = new FileModel();
      // Undeclared exception!
      try { 
        analyzerJava0.analyzeFile((File) null, fileModel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }
}
