/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 18 11:04:32 GMT 2020
 */

package teapot.pga;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import teapot.pga.FileModel;
import teapot.pga.SumModel;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SumModel_ESTest extends SumModel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SumModel sumModel0 = new SumModel();
      sumModel0.setFiles((-3437L));
      long long0 = sumModel0.getFiles();
      assertEquals((-3437L), long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SumModel sumModel0 = new SumModel();
      // Undeclared exception!
      try { 
        sumModel0.add((FileModel) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("teapot.pga.FileModel", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SumModel sumModel0 = new SumModel();
      sumModel0.countfiles();
      long long0 = sumModel0.getFiles();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SumModel sumModel0 = new SumModel();
      String string0 = sumModel0.toString();
      assertEquals("SumModel(super=FileModel(fileName=, fileSize=0, fileType=0, lines=0, whiteLines=0, commentLines=0, normalLines=0), files=0)", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SumModel sumModel0 = new SumModel();
      sumModel0.add(sumModel0);
      assertEquals(1L, sumModel0.getFiles());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SumModel sumModel0 = new SumModel();
      long long0 = sumModel0.getFiles();
      assertEquals(0L, long0);
  }
}
